###############################################################################
#                          Generated on phpdocker.io                          #
#
# Generic instructions: docker-compose up -d
#
# webDiplomacy instructions:
# - Copy config.sample.php to config.php
# - Run install/FullInstall/FullInstall.sql
# - Register user account, use http://localhost:43001 to access registration mail
# - Go to http://localhost:43000/gamemaster.php?gameMasterSecret= to set self as admin
# - Go to http://localhost:43000/admincp.php and enable maintenance mode
# - In the admin CP run the Clear variant caches command to ensure variants get installed fresh
# - Go to http://localhost:43000/datc.php and run batch test
# - Go to http://localhost:43000/admincp.php and disable maintenance mode
# Server is ready for dev work
#
###############################################################################
version: "3.1"
services:
  memcached:
    image: "memcached:alpine"
    ports:
      - "11211:11211"

  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - "8025:8025"

  mariadb:
    image: "mariadb:10.6"
    restart: always
    working_dir: /application
    volumes:
      - "./:/application"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - ${PHPMYADMIN_PORT:-8080}:80
    environment:
      - PMA_ARBITRARY=1

  clickhouse:
    image: "yandex/clickhouse-server:latest"

  # This is necessary for doing live React dev for the new board, but isn't needed after doing a build
  # if the nginx config is changed to not redirect /beta/ to port 3000:
  beta:
    image: "node:16.15.1-alpine3.14"
    container_name: webdiplomacy-beta
    working_dir: /application
    volumes:
      - "./beta-src:/application"
    ports:
      - "3000"
    command: >
      sh -c "npm install &&
              npm run start"

  php-fpm:
    build: phpdocker/php-fpm
    working_dir: /application
    volumes:
      - "./:/application"
      - "./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini"
    command: /bin/sh -c "install/gamemaster-entrypoint.sh"
    #environment:
    #    PHP_IDE_CONFIG: "serverName=Docker"
    #    XDEBUG_MODE: debug
    #    XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    #    XDEBUG_SESSION: 1

  webserver:
      image: 'nginx:alpine'
      working_dir: /application
      volumes:
          - './:/application'
          - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      ports:
          - '${WEBDIP_PORT:-80}:80'

  soketi:
    container_name: "soketi_server"
    restart: unless-stopped
    image: "quay.io/soketi/soketi:0.17-16-alpine"
    ports:
      - "${SOKETI_PORT:-6001}:6001"
      - "${SOKETI_METRICS_SERVER_PORT:-9601}:9601"
    #environment:
    #    - DEBUG='${DEBUG:-1}'
    #    - PUSHER_APP_ID='webdiplomacy'
    #    - PUSHER_APP_KEY='webdiplomacykey123'
    #    - PUSHER_APP_SECRET='webdiplomacysecret123'
    #    - PUSHER_HOST='${PUSHER_HOST:-127.0.0.1}'
    #    - PUSHER_PORT= '${PUSHER_PORT:-6001}'
    #    - PUSHER_SCHEME='${PUSHER_SCHEME:-http}' # or https
    #    - METRICS_SERVER_PORT=${METRICS_SERVER_PORT-9601}
    #    - DEFAULT_APP_ENABLE_CLIENT_MESSAGES=true
